/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    Greeting: typeof import('./src/components/ui/Greeting.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    Navbar: typeof import('./src/components/ui/Navbar.vue')['default']
    RootLayout: typeof import('./src/components/layouts/RootLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
