services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  flask:
    container_name: flask
    build: ./server
    volumes:
      - ./server:/app/
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
  redis_data: