name: CI workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  flask:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bacala.db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./server
      - name: Run Tests
        run: pytest
        working-directory: ./server
